# Generated by Django 3.2.5 on 2021-07-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210713_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='work',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
